### ISSUE TITLE
Cert Error: no private key

### ISSUE THREAD

**Issue by dncmn** [sideshow/apns2#110] opened 2018-07-03 13:59 UTC
cert, err := certificate.FromPemFile("./test/apns-dev-cert.pem", "1234")
	if err != nil {
		t.Fatal("Cert Error:", err)
}
can't generage cert
Is there anything wrong in generating cert??
according to 
https://www.cnblogs.com/warrior/p/5886272.html

**Comment by sideshow** [comment] 2018-07-07 23:09
This means there is a problem with your cert not the library. The error is because it doesn't contain the private key.

You should be able to confirm this by inspecting the `./test/apns-dev-cert.pem` file. To work correctly the .pem file requires a certificate and a private key. The private key section in the .pem file will look something like this.

```
-----BEGIN PRIVATE KEY-----
...
```

Make sure you're exporting the .p12 from the same machine you generated the push cert from, otherwise it won't contain the private key.

**Comment by sideshow** [comment] 2018-07-07 23:10
I will close this issue off since its not a bug. Thanks

**Closed by sideshow** 2018-07-07 23:10 UTC

**Comment by PiotrKozimor** [comment] 2022-07-26 13:44
If anyone will struggle: https://fluffy.es/keychain-cant-export-to-p12/. The thing I missed was selecting the right keychain (default "login" for me) so that imported certificate is bound to key created as a part of certificate request creation.
